version: '3.8'

services:
  opensearch-master:
    image: opensearchproject/opensearch:2.19.0
    container_name: opensearch-master
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-master
      - discovery.seed_hosts=opensearch-master,opensearch-hot,opensearch-hot-2,opensearch-warm,opensearch-warm-2
      - cluster.initial_master_nodes=opensearch-master
      - node.roles=cluster_manager
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Str0ng!Passw0rd2025#"
    volumes:
      - "./configs/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "opensearch-master:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certs:ro"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default

  opensearch-hot:
    image: opensearchproject/opensearch:2.19.0
    container_name: opensearch-hot
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-hot
      - discovery.seed_hosts=opensearch-master,opensearch-hot,opensearch-hot-2,opensearch-warm,opensearch-warm-2
      - cluster.initial_master_nodes=opensearch-master
      - node.roles=data
      - node.attr.temp=hot
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Str0ng!Passw0rd2025#"
    volumes:
      - "./configs/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "opensearch-hot:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certs:ro"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default

  opensearch-hot-2:
    image: opensearchproject/opensearch:2.19.0
    container_name: opensearch-hot-2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-hot-2
      - discovery.seed_hosts=opensearch-master,opensearch-hot,opensearch-hot-2,opensearch-warm,opensearch-warm-2
      - cluster.initial_master_nodes=opensearch-master
      - node.roles=data
      - node.attr.temp=hot
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Str0ng!Passw0rd2025#"
    volumes:
      - "./configs/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "opensearch-hot-2:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certs:ro"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default

  opensearch-warm:
    image: opensearchproject/opensearch:2.19.0
    container_name: opensearch-warm
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-warm
      - discovery.seed_hosts=opensearch-master,opensearch-hot,opensearch-hot-2,opensearch-warm,opensearch-warm-2
      - cluster.initial_master_nodes=opensearch-master
      - node.roles=data
      - node.attr.temp=warm
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Str0ng!Passw0rd2025#"
    volumes:
      - "./configs/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "opensearch-warm:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certs:ro"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default

  opensearch-warm-2:
    image: opensearchproject/opensearch:2.19.0
    container_name: opensearch-warm-2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-warm-2
      - discovery.seed_hosts=opensearch-master,opensearch-hot,opensearch-hot-2,opensearch-warm,opensearch-warm-2
      - cluster.initial_master_nodes=opensearch-master
      - node.roles=data
      - node.attr.temp=warm
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Str0ng!Passw0rd2025#"
    volumes:
      - "./configs/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "opensearch-warm-2:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certs:ro"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-master:9200"]'
    volumes:
      - "./certs:/usr/share/opensearch-dashboards/config/certificates"
      - "./configs/opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
    depends_on:
      - opensearch-master
    networks:
      - default

volumes:
  opensearch-hot:
  opensearch-hot-2:
  opensearch-warm:
  opensearch-warm-2:
  opensearch-master:

networks:
  default:
    name: opensearch-net
    external: true
